-- EasySwitchLua (dist) — generated by build.lua, do not edit.
-- Source: https://github.com/kamion/EasySwitchLua
-- License: MIT

local _modules = {}
local function _require(name)
    local m = _modules[name]
    if not m then error("[EasySwitch] module not found: " .. name) end
    return m
end

_modules["src.eventManager"] = (function()
local EventManager = {}

function EventManager.new()
    local events = {
        beforeExecute     = {},
        afterExecute      = {},
        error             = {},
        cacheHit          = {},
        cacheMiss         = {},
        middlewareStart   = {},
        middlewareEnd     = {},
        noMatch           = {},
        beforeCheckFailed = {},
    }

    return {
        on = function(event, callback)
            if not events[event] then
                error("Unknown event: '" .. tostring(event) .. "'", 2)
            end
            events[event][#events[event] + 1] = callback
        end,

        emit = function(event, ...)
            local array = events[event]
            if not array then return end
            for i = 1, #array do
                local ok, err = pcall(array[i], ...)
                if not ok then
                    print("[EasySwitch] Event error in '" .. event .. "':", err)
                end
            end
        end,

        clear = function(event)
            if event then
                if events[event] then events[event] = {} end
            else
                for k in pairs(events) do events[k] = {} end
            end
        end,
    }
end

return EventManager

end)()

_modules["src.middlewareManager"] = (function()
local MiddlewareManager = {}

function MiddlewareManager.new(eventManager)
    local middlewares = {}
    local compiled_middleware
    local middleware_hash = ""

    local function hashMiddlewares()
        local hash, length = {}, #middlewares

        if length == 0 then
            return ""
        end

        for i = 1, length do
            local middleware = middlewares[i]
            hash[i] = tostring(middleware)
        end

        return table.concat(hash)
    end

    local function compileMiddlewares()
        local new_hash = hashMiddlewares()
        if new_hash == middleware_hash and compiled_middleware then
            return compiled_middleware
        end

        middleware_hash = new_hash

        return function(value)
            local current = value
            local length = #middlewares

            if length == 0 then
                return value
            end

            for i = 1, length do
                local middleware = middlewares[i]
                local success, result = pcall(middleware, current)
                if not success then
                    eventManager.emit("error", "middleware", result)
                    current = value
                elseif result ~= nil then
                    current = result
                end
            end
            return current
        end
    end

    return {
        add = function(middleware)
            if type(middleware) ~= "function" then
                error("Middleware must be a function", 2)
            end

            middlewares[#middlewares + 1] = middleware
            compiled_middleware = nil -- Force recompilation
        end,

        execute = function(value)
            if #middlewares == 0 then
                return value
            end

            eventManager.emit("middlewareStart", value)
            if not compiled_middleware then
                compiled_middleware = compileMiddlewares()
            end

            local result = compiled_middleware(value)
            eventManager.emit("middlewareEnd", result)
            return result
        end,

        count = function()
            return #middlewares
        end
    }
end

return MiddlewareManager
end)()

_modules["src.patterns"] = (function()
-- Pattern vocabulary for structural dispatch in EasySwitchLua.
-- Patterns are tagged tables (PATTERN_MT metatable) carrying a _match function.
-- Plain tables with string keys are also treated as partial table matchers.

local P = {}

local PATTERN_MT = {}
PATTERN_MT.__index = PATTERN_MT
PATTERN_MT.__tostring = function(self) return self._name end

-- Lua < 5.3 / LuaJIT / Luau polyfill for math.type
local math_type = math.type or function(n)
    if type(n) ~= "number" then return nil end
    if n ~= n or n == math.huge or n == -math.huge then return "float" end
    return (math.floor(n) == n) and "integer" or "float"
end

local function new_pattern(match_fn, name)
    return setmetatable({ _match = match_fn, _name = name }, PATTERN_MT)
end

-- Returns true if v is a pattern descriptor (created by this module)
local function is_pattern(v)
    return type(v) == "table" and getmetatable(v) == PATTERN_MT
end

-- Recursive match: pattern OR literal OR partial table
local function match(pat, value)
    if is_pattern(pat) then
        return pat._match(value)
    elseif type(pat) == "table" then
        if type(value) ~= "table" then return false end
        for k, v in pairs(pat) do
            if not match(v, value[k]) then return false end
        end
        return true
    else
        return pat == value
    end
end

-- ── Type sentinels ────────────────────────────────────────────────────────────

P.string  = new_pattern(function(v) return type(v) == "string"   end, "P.string")
P.number  = new_pattern(function(v) return type(v) == "number"   end, "P.number")
P.boolean = new_pattern(function(v) return type(v) == "boolean"  end, "P.boolean")
P.table   = new_pattern(function(v) return type(v) == "table"    end, "P.table")
P.func    = new_pattern(function(v) return type(v) == "function" end, "P.func")
P.nil_    = new_pattern(function(v) return v == nil               end, "P.nil_")
P.any     = new_pattern(function(_) return true                   end, "P.any")
P.integer = new_pattern(function(v) return math_type(v) == "integer" end, "P.integer")
P.float   = new_pattern(function(v) return math_type(v) == "float"   end, "P.float")

-- ── Combinators ───────────────────────────────────────────────────────────────

-- P.when(fn) — arbitrary predicate
function P.when(fn)
    assert(type(fn) == "function", "P.when expects a function")
    return new_pattern(fn, "P.when(...)")
end

-- P.any_of(a, b, ...) — union of literals and/or patterns
function P.any_of(...)
    local options = { ... }
    return new_pattern(function(v)
        for i = 1, #options do
            if match(options[i], v) then return true end
        end
        return false
    end, "P.any_of(...)")
end

-- P.not_(pat) — negation
function P.not_(pat)
    return new_pattern(function(v) return not match(pat, v) end, "P.not_(...)")
end

-- P.and_(a, b, ...) / P.all_of — intersection: all patterns must match
function P.and_(...)
    local pats = { ... }
    assert(#pats >= 1, "P.and_ expects at least one argument")
    return new_pattern(function(v)
        for i = 1, #pats do
            if not match(pats[i], v) then return false end
        end
        return true
    end, "P.and_(...)")
end
P.all_of = P.and_

-- P.between(min, max) — inclusive numeric range
function P.between(min, max)
    assert(type(min) == "number" and type(max) == "number", "P.between expects two numbers")
    return new_pattern(function(v)
        return type(v) == "number" and v >= min and v <= max
    end, "P.between(" .. min .. ", " .. max .. ")")
end

-- P.shape(tbl) — strict table match: all keys in tbl must match AND no extra keys allowed
function P.shape(tbl)
    assert(type(tbl) == "table", "P.shape expects a table")
    return new_pattern(function(v)
        if type(v) ~= "table" then return false end
        for k, pat in pairs(tbl) do
            if not match(pat, v[k]) then return false end
        end
        for k in pairs(v) do
            if tbl[k] == nil then return false end
        end
        return true
    end, "P.shape(...)")
end

-- P.string_match(lua_pattern) — string.match against a Lua pattern
function P.string_match(lua_pattern)
    assert(type(lua_pattern) == "string", "P.string_match expects a string pattern")
    return new_pattern(function(v)
        return type(v) == "string" and string.match(v, lua_pattern) ~= nil
    end, "P.string_match(" .. lua_pattern .. ")")
end

-- P.array(item_pat) — non-empty sequential table where every element matches item_pat
function P.array(item_pat)
    return new_pattern(function(v)
        if type(v) ~= "table" or #v == 0 then return false end
        for i = 1, #v do
            if not match(item_pat, v[i]) then return false end
        end
        return true
    end, "P.array(...)")
end

-- ── Exports ───────────────────────────────────────────────────────────────────

P.is_pattern = is_pattern
P.match      = match

return P

end)()

_modules["src.actionManager"] = (function()
local P = _require("src.patterns")

local ActionManager = {}

function ActionManager.new(maxCases, fallthrough_sentinel)
    local literal_dispatch = {}  -- O(1) hash, results are cacheable
    local pattern_rules    = {}  -- ordered list, iterated, not cached
    local default_action
    local case_count  = 0
    local max_cases   = maxCases or 100
    local has_patterns = false

    local function guard_count(n)
        if case_count + n > max_cases then
            error("Too many cases (max " .. max_cases .. ")", 3)
        end
    end

    return {
        add = function(cases, action)
            if type(action) ~= "function" then
                error("Action must be a function", 2)
            end

            if P.is_pattern(cases) then
                -- P.string, P.when(fn), P.any_of(...), etc.
                guard_count(1)
                has_patterns = true
                pattern_rules[#pattern_rules + 1] = { pat = cases, action = action }
                case_count = case_count + 1

            elseif type(cases) == "table" then
                if #cases > 0 then
                    -- {"a", "b", "c"} → array of literals (backward-compat)
                    guard_count(#cases)
                    for i = 1, #cases do
                        literal_dispatch[cases[i]] = action
                    end
                    case_count = case_count + #cases
                else
                    -- {kind="circle", r=P.number} → partial table pattern
                    guard_count(1)
                    has_patterns = true
                    pattern_rules[#pattern_rules + 1] = { pat = cases, action = action }
                    case_count = case_count + 1
                end

            else
                -- "hello", 42, true → single literal
                guard_count(1)
                literal_dispatch[cases] = action
                case_count = case_count + 1
            end
        end,

        -- Returns: result, cacheable, matched
        -- cacheable=true only for literal hits (safe to cache by key)
        -- matched=false when nothing handled the value (noMatch event)
        -- An action may return fallthrough_sentinel to continue matching.
        execute = function(value)
            local ever_matched = false

            local action = literal_dispatch[value]
            if action then
                ever_matched = true
                local result = action(value)
                if result ~= fallthrough_sentinel then
                    return result, true, true
                end
            end

            if has_patterns then
                for i = 1, #pattern_rules do
                    local rule = pattern_rules[i]
                    if P.match(rule.pat, value) then
                        ever_matched = true
                        local result = rule.action(value)
                        if result ~= fallthrough_sentinel then
                            return result, false, true
                        end
                    end
                end
            end

            if default_action then
                return default_action(value), false, true
            end

            return nil, false, ever_matched
        end,

        setDefault = function(action)
            if type(action) ~= "function" then
                error("Default action must be a function", 2)
            end
            default_action = action
        end,

        hasAction = function(value)
            return literal_dispatch[value] ~= nil
        end,

        hasPatterns = function()
            return has_patterns
        end,
    }
end

return ActionManager

end)()

_modules["src.cacheManager"] = (function()
local CacheManager = {}

function CacheManager.new(eventManager)
    local cache = setmetatable({}, {__mode = "kv"})

    return {
        get = function(value)
            local v = cache[value]
            if v ~= nil then
                eventManager.emit("cacheHit", value, v)
                return v
            end

            eventManager.emit("cacheMiss", value)
            return nil
        end,

        set = function(value, result)
            if result ~= nil then
                cache[value] = result
            end
        end,

        update = function(value, fn)
            if cache[value] ~= nil then
                local newResult = fn(cache[value])
                if newResult ~= nil then
                    cache[value] = newResult
                end
            end
        end,

        clear = function()
            cache = setmetatable({}, {__mode = "kv"})
        end
    }
end

return CacheManager
end)()

_modules["src.switch"] = (function()
-- Pure switch instance factory — zero global state.
-- All managers are created fresh per instance.

local EventManager      = _require("src.eventManager")
local MiddlewareManager = _require("src.middlewareManager")
local ActionManager     = _require("src.actionManager")
local CacheManager      = _require("src.cacheManager")
local P                 = _require("src.patterns")

local Switch = {}

-- Sentinel returned by an action to continue matching subsequent cases.
local FALLTHROUGH = setmetatable({}, {
    __tostring = function() return "EasySwitch.FALLTHROUGH" end,
})
Switch.FALLTHROUGH = FALLTHROUGH

function Switch.new(options)
    local opts = options or {}

    local eventManager      = EventManager.new()
    local middlewareManager = MiddlewareManager.new(eventManager)
    local actionManager     = ActionManager.new(opts.maxCases, FALLTHROUGH)
    local cacheManager      = CacheManager.new(eventManager)

    local beforeCheck = function() return true end

    local instance = {}

    -- ── Events ────────────────────────────────────────────────────────────────

    function instance:on(event, callback)
        eventManager.on(event, callback)
        return self
    end

    -- ── Cases ─────────────────────────────────────────────────────────────────

    -- 2-arg form : when(cases, action)
    -- 3-arg form : when(cases, guard, action) — guard(v) must return true to proceed
    function instance:when(cases, guard_or_action, action)
        if type(action) == "function" then
            local guard = guard_or_action
            actionManager.add(P.when(function(v)
                return P.match(cases, v) and guard(v)
            end), action)
        else
            actionManager.add(cases, guard_or_action)
        end
        return self
    end

    function instance:default(action)
        actionManager.setDefault(action)
        return self
    end

    -- ── Middleware ────────────────────────────────────────────────────────────

    function instance:use(middleware)
        middlewareManager.add(middleware)
        return self
    end

    -- ── Gate ──────────────────────────────────────────────────────────────────

    function instance:before(checkFunction)
        beforeCheck = checkFunction or beforeCheck
        return self
    end

    -- ── Execution ─────────────────────────────────────────────────────────────

    function instance:execute(value)
        eventManager.emit("beforeExecute", value)

        -- Cache check — only hits for scalar keys; table refs almost never reuse
        local cached = cacheManager.get(value)
        if cached ~= nil then
            eventManager.emit("afterExecute", value, cached)
            return cached
        end

        if not beforeCheck(value) then
            eventManager.emit("beforeCheckFailed", value)
            return nil
        end

        local final_value = middlewareManager.execute(value)

        -- result, cacheable, matched
        local ok, result, cacheable, matched = pcall(actionManager.execute, final_value)
        if not ok then
            eventManager.emit("error", "action", result)
            eventManager.emit("afterExecute", value, nil)
            return nil
        end

        if not matched then
            eventManager.emit("noMatch", value)
        end

        if cacheable and result ~= nil then
            cacheManager.set(value, result)
        end

        eventManager.emit("afterExecute", value, result)
        return result
    end

    -- ── Sentinel ──────────────────────────────────────────────────────────────

    instance.FALLTHROUGH = FALLTHROUGH

    -- ── Utilities ─────────────────────────────────────────────────────────────

    function instance:clearCache()
        cacheManager.clear()
        return self
    end

    function instance:clearEvents(event)
        eventManager.clear(event)
        return self
    end

    return instance
end

return Switch

end)()

_modules["src.registry"] = (function()
-- Optional named registry — wraps Switch.new() and stores instances by name.
-- Kept separate so anonymous usage (EasySwitch.new) has zero registry overhead.
-- store is always mutated in-place so Registry.registered stays valid.

local Switch = _require("src.switch")

local Registry = {}

local store = {}
Registry.registered = store

function Registry.create(name, options)
    if type(name) ~= "string" or name == "" then
        error("Registry name must be a non-empty string. Use EasySwitch.new() for anonymous switches.", 2)
    end
    if store[name] then
        error("Switch [" .. name .. "] is already registered", 2)
    end
    local instance = Switch.new(options)
    store[name] = instance
    return instance
end

function Registry.get(name)
    if name then
        return store[name]
    end
    if not next(store) then return nil, 0 end
    local result, count = {}, 0
    for k, v in pairs(store) do
        count = count + 1
        result[k] = v
    end
    return result, count
end

function Registry.clear(name)
    if name then
        store[name] = nil
    else
        for k in pairs(store) do store[k] = nil end
    end
end

return Registry

end)()

_modules["src.init"] = (function()
-- Main entry point: combines anonymous factory, named registry, and pattern vocabulary.
--
-- Usage:
--   local EasySwitch = require("easyswitch")
--
--   -- Anonymous (recommended, fully portable)
--   local sw = EasySwitch.new()
--
--   -- Named registry (backward-compatible)
--   local sw = EasySwitch("menu")
--
--   -- Patterns
--   local P = EasySwitch.P

local Switch   = _require("src.switch")
local Registry = _require("src.registry")
local P        = _require("src.patterns")

local EasySwitch = setmetatable({
    new         = Switch.new,
    P           = P,
    FALLTHROUGH = Switch.FALLTHROUGH,
    get         = Registry.get,
    clear       = Registry.clear,
    registered  = Registry.registered,
}, {
    -- EasySwitch("name", opts) → named registry mode (backward-compat)
    __call = function(_, name, options)
        return Registry.create(name, options)
    end,
})

return EasySwitch

end)()

local _es = _modules["src.init"]
rawset(_G, 'EasySwitch', _es)
return _es